#!/usr/bin/env perl

use strict;
use warnings;

sub on_init {
   my ($self) = @_;

   # $self->bind_action ("C-plus", "%:increase")
   #    or warn "unable to register 'C-plus' as font-size increase hotkey\n";
   # $self->bind_action ("C-minus", "%:decrease")
   #    or warn "unable to register 'C-minus' as font-size decrease hotkey\n";
   # $self->bind_action ("C-0", "%:reset")
   #    or warn "unable to register 'C-0' as font-size reset hotkey\n";
}

sub on_start
{
    my ($self) = @_;

    # $self->{step} = $self->x_resource("%.step") || 1;

    # foreach my $type (qw(font boldFont italicFont boldItalicFont)) {
    #     $self->{$type} = $self->x_resource($type) || "undef";
    # }
}

sub on_action
{
    my ($self, $action) = @_;

    # if($action eq "droid"){
    #   my $fn = "xft:Droid Sans Mono Dotted-10.2";
    #   # print '\033]710;' . $fn . '\033\\';
    #   set_font($self, $fn);
    # }elsif($action eq "dina"){
    #   my $fn = "xft:Dina-9";
    #   set_font($self, $fn);
    #   # print '\033]710;' . $fn . '\033\\';
    # }

    my $fn = $action;
    set_font($self, $action);
}

sub set_font
{
  my ($term, $fn) = @_;

  $term->cmd_parse("\033]710;" . $fn . "\033\\");
}
