#!/bin/sh

## subst all commas(,) with newline in the rule file generated by libreoffice
# path of rule file generated by libreoffice. uses comma as separator
rule_kana_libre="myazik-kana-libreoffice.txt"
rule_kana="rules/11-myazik-kana.txt"

sed 's/,/\
/g' "$rule_kana_libre" > "$rule_kana"

rule_sym_libre="myazik-sym-libreoffice.txt"
rule_sym="rules/21-myazik-sym.txt"

sed 's/あ/\
/g' "$rule_sym_libre" > "$rule_sym"


## merge rule files into one file
rule_out="myazik-all"

# initialize output file
echo -n > "$rule_out"

# merge all files under rule/
for f in rules/*; do
  cat "$f" >> "$rule_out"
done


## generate scheme file of rules (for uim-skk and ddskk)
gosh rule-list-generator.scm myazik-all "${rule_out}_utf8.scm"
iconv -f utf8 -t eucjp "${rule_out}_utf8.scm" > "${rule_out}.scm"

## generate rule file for Mozc (replace space by tab)
sed 's/ /\t/g' myazik-all > myazik-all-mozc
