#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/tpdeb86x/.Xmodmap" <- This is done in ~/.xinitrc

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# amixer set Master unmute &
xcompmgr -c &
feh --bg-scale ~/.fluxbox/backgrounds/manjaro_neo_1920x1080_by_nestortura-d7ynfza.png &
xset b off &
xset r rate 200 38 &
# wmbattery -w 50 &
sleep 3 && fdpowermon &
sleep 3 && volumeicon &
# sudo ~/sucripts/myifup &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/tpdeb86x/.fluxbox/log"
