#!/bin/sh

set_bg() {
    for bg in ~/.config/background.*; do
        if [ -f "$bg" ]; then
            swaybg -m fill -i "$bg" >/dev/null 2>&1 &
            return
        fi
    done
    swaybg -c '#21282b' >/dev/null 2>&1 &
}
set_bg

sfwbar -f myt2.config &
foot -s &
uim-xim &

