#!/bin/sh

d=~/media/music/trainsound/
m=~/.fluxbox/musicmenu

cd "$d"

# find . | grep -i -e mp3 -e m4a -e flac -e webm | perl -pe 'chomp; s/^\.\///; $f=$_; $f=~s/\)/\\\\)/g; s#(.*)#[exec] ($f) {mocp -l "'"$d"'/\1"}\n#' | tee "$m"
{ find . -mindepth 2 | sort -t '/'; find . -mindepth 1 -maxdepth 1 | sort -t '/'; } | \
    grep -i -e mp3 -e m4a -e flac -e wav -e webm -e mp4 | \
    perl -pe 'chomp; s/^\.\///; $f=$_; $f=~s/\)/\\)/g; $f=~s#([^/])([^/]*)/#\1/#g; s#(.*)#[exec] ($f) {mocp -l "'"$d"'/\1"}\n#' | \
    tee "$m"
