#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox

# or if you want to keep a log:
