(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'mozc)
(define default-im-name 'mozc)
(define enabled-im-list '(skk py mozc))
(define enable-im-switch? #t)
(define switch-im-key '("<Control>zenkaku-hankaku"))
(define switch-im-key? (make-key-predicate '("<Control>zenkaku-hankaku")))
(define switch-im-skip-direct-im? #t)
(define enable-im-toggle? #t)
(define toggle-im-key '("<IgnoreShift><Control>1"))
(define toggle-im-key? (make-key-predicate '("<IgnoreShift><Control>1")))
(define toggle-im-alt-im 'py)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #t)
(define bridge-show-with? 'mode)
(define bridge-show-input-state-time-length 3)
