(define skk-return-key '(generic-return-key))
(define skk-return-key? (make-key-predicate '(generic-return-key?)))
(define skk-latin-conv-key '("<IgnoreCase>j"))
(define skk-latin-conv-key? (make-key-predicate '("<IgnoreCase>j")))
(define skk-conv-wide-latin-key '("<IgnoreCase><Control>q"))
(define skk-conv-wide-latin-key? (make-key-predicate '("<IgnoreCase><Control>q")))
(define skk-conv-opposite-case-key '("<IgnoreCase><Control>u"))
(define skk-conv-opposite-case-key? (make-key-predicate '("<IgnoreCase><Control>u")))
(define skk-begin-completion-key '("<IgnoreCase><Control>i" "<Shift>tab" "right"))
(define skk-begin-completion-key? (make-key-predicate '("<IgnoreCase><Control>i" "<Shift>tab" "right")))
(define skk-next-completion-key '("<IgnoreShift>." "tab" "<IgnoreCase><Control>i" "<Shift>tab"))
(define skk-next-completion-key? (make-key-predicate '("<IgnoreShift>." "tab" "<IgnoreCase><Control>i" "<Shift>tab")))
(define skk-prev-completion-key '(","))
(define skk-prev-completion-key? (make-key-predicate '(",")))
(define skk-new-completion-from-current-comp-key '("<Alt>tab" "<IgnoreCase><Control><Alt>i"))
(define skk-new-completion-from-current-comp-key? (make-key-predicate '("<Alt>tab" "<IgnoreCase><Control><Alt>i")))
(define skk-special-midashi-key '())
(define skk-special-midashi-key? (make-key-predicate '()))
(define skk-vi-escape-key '("escape" "<Control>["))
(define skk-vi-escape-key? (make-key-predicate '("escape" "<Control>[")))
(define skk-state-direct-no-preedit-nop-key '("<IgnoreCase><Control>j"))
(define skk-state-direct-no-preedit-nop-key? (make-key-predicate '("<IgnoreCase><Control>j")))
(define skk-purge-candidate-key '("<IgnoreCase><Shift><Control>x" "<IgnoreShift><Control>-"))
(define skk-purge-candidate-key? (make-key-predicate '("<IgnoreCase><Shift><Control>x" "<IgnoreShift><Control>-")))
