# This is a drop-in file corresponding to /etc/systemd/logind.conf
# Directory name (logind.conf.d) is significant but the file name (my.conf) is not

[Login]
HandlePowerKey=hibernate
HandleLidSwitch=suspend
