#!/bin/sh

# UO for tab

w3mdir=~/.w3m/

if [ "$MYKBD" = colemakdh ]; then
    keymap_file=$w3mdir/keymap_colemakdh
    h=k j=n k=e l=i  H=K J=N K=E L=I  n=j N=J  i=l I=L
else
    keymap_file=$w3mdir/keymap_qwerty
    h=h j=j k=k l=l  H=H J=J K=K L=L  n=n N=N  i=i I=I
fi

del='^[[3~'

text="##### DO NOT EDIT (generated by $0)


### Movement
# Scroll screen
keymap SPC   NEXT_PAGE
keymap DEL   PREV_PAGE
keymap $J    NEXT_PAGE
keymap $K    PREV_PAGE
keymap $j    UP
keymap $k    DOWN
keymap $H    LEFT
keymap $L    RIGHT
# Cursor movement
keymap DOWN  MOVE_DOWN1
keymap UP    MOVE_UP1
keymap $del  NEXT_WORD
keymap w     NEXT_WORD
keymap b     PREV_WORD
keymap 0     LINE_BEGIN
keymap $     LINE_END


### Links
keymap $h    PREV_LINK
keymap $l    NEXT_LINK
keymap f     LINK_BEGIN
keymap F     MOVE_LIST_MENU
# keymap c-i   INFO
# keymap x     SET_OPTION display_link_number=0; RESHAPE
# keymap X     SET_OPTION display_link_number=1; RESHAPE


# Buffers/history
keymap u     BACK
keymap R     RELOAD
keymap $i    GOTO
keymap $I    HISTORY
keymap ESC-h GOTO_HOME


### Tabs
keymap t     NEW_TAB
keymap T     TAB_MENU
keymap +     NEXT_TAB
keymap -     PREV_TAB


### Misc
keymap U     GOTO
keymap r     RESHAPE
keymap o     GOTO_HOME
keymap c-h   HELP
keymap ?     HELP
keymap O     OPTIONS
keymap H     HISTORY
keymap :     COMMAND


# Bookmarks
keymap B     VIEW_BOOKMARK
keymap ESC-a ADD_BOOKMARK


# Search
keymap /     ISEARCH
# keymap ?     ISEARCH_BACK
keymap $n    SEARCH_NEXT
keymap $N    SEARCH_PREV


"

echo "$text" > "$keymap_file"
