(define skk-on-key '("zenkaku-hankaku" "<IgnoreShift><Control>;"))
(define skk-on-key? (make-key-predicate '("zenkaku-hankaku" "<IgnoreShift><Control>;")))
(define skk-latin-key '("zenkaku-hankaku" "<IgnoreShift><Control>;"))
(define skk-latin-key? (make-key-predicate '("zenkaku-hankaku" "<IgnoreShift><Control>;")))
(define skk-wide-latin-key '("<IgnoreCase><Control>j"))
(define skk-wide-latin-key? (make-key-predicate '("<IgnoreCase><Control>j")))
(define skk-kcode-input-key '("yen"))
(define skk-kcode-input-key? (make-key-predicate '("yen")))
(define skk-kanji-mode-key '())
(define skk-kanji-mode-key? (make-key-predicate '()))
(define skk-hankaku-kana-key '("<IgnoreCase><Control>q"))
(define skk-hankaku-kana-key? (make-key-predicate '("<IgnoreCase><Control>q")))
(define skk-kana-toggle-key '("<IgnoreCase><Shift>j"))
(define skk-kana-toggle-key? (make-key-predicate '("<IgnoreCase><Shift>j")))
(define skk-begin-conv-key '(" " "down"))
(define skk-begin-conv-key? (make-key-predicate '(" " "down")))
(define skk-commit-key '("<IgnoreCase><Control>j"))
(define skk-commit-key? (make-key-predicate '("<IgnoreCase><Control>j")))
(define skk-cancel-key '(generic-cancel-key))
(define skk-cancel-key? (make-key-predicate '(generic-cancel-key?)))
(define skk-sticky-key '())
(define skk-sticky-key? (make-key-predicate '()))
